### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by dennisleexyz** [GideonWolfe/canvas-tui#1]
How do you actually install this thing? The install script just writes the config file. I'm new to go, I just tried to `go build main.go`, but:
```sh
# command-line-arguments
./main.go:31:35: undefined: Course
./main.go:94:36: undefined: placeholder
./main.go:104: undefined: Course
./main.go:172:18: undefined: Course
./main.go:172:27: undefined: fetchCourses
./main.go:173:23: undefined: Course
./main.go:188:29: undefined: Assignment
./main.go:191:30: undefined: Announcement
./main.go:194:33: undefined: AssignmentGroup
./main.go:200:54: undefined: fetchAssignments
./main.go:200:54: too many errors
```
Sorry for the dumb question.

**Comment by GideonWolfe** [comment]
Not a dumb question at all! To build the program into a single executable, run `go build .` so it can see all the files in that directory. `go run .` will just start it so you can test
