### ISSUE TITLE
error when running `go run .`

### ISSUE THREAD

**Issue by SingularisArt** [GideonWolfe/canvas-tui#7]
Hello.

When I installed this repo using `git clone https://github.com/GideonWolfe/canvas-tui/`, I then ran:

```go
GO111MODULE=on go get github.com/spf13/viper
go get github.com/gizak/termui
go get github.com/gizak/termui/widgets
go get github.com/grokify/html-strip-tags-go
```

and they all worked. After that, I ran `go build`.
Finally, when I ran `go run .`, I get this error:

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV; segmentation violation code=0x1 addr=0x20 pc=0x8305110]
goroutine 1 [running]:
main.fetchCourses()
    canvas/fetchCourses.go:153 +0x360
main.main()
    canvas/main.go:172 +0x360
exit status 2
```

**Comment by SingularisArt** [comment]
I fixed the error. I just put the wrong domain.
But, not all of my classes are showing. Only 3 out of 7 are showing.
Can someone help me? I don't know much `go` at all!

**Comment by GideonWolfe** [comment]
Sorry about the issues, I'm not even a student any longer so I have no access to Canvas. However I was unable to resolve these issues after reaching out to the Canvas dev team, I had multiple classes that wouldn't show, or would show incorrectly. This was especially a problem with "uncommon" classes like TA, Training, Research, etc.

**Comment by SingularisArt** [comment]
Alright. Also, where did you learn `go` because I'm intrigued into learning it after seeing what it can do?

**Comment by GideonWolfe** [comment]
I learned it for the express purpose of making this application and I haven't really used it since! Mostly just googling stuff and reading the docs, no specific tutorial I can point to unfortunately.

**Comment by SingularisArt** [comment]
Great. Thanks!
